Change the response structure
flexbase-eng/flexbase-client pull request #41
Opened 2022-09-22 17:22 UTC by Mariana0711

In this PR I changed the response structure for the `getCompanyPayments` function so if the result is success I only get the payments array instead all the object `({ success: true, payments: [...]})`,

2022-09-22 17:30 UTC, xXAndrexPereXx submitted a review, later dismissed

2022-09-22 17:41 UTC, alegoos requested changes

2022-09-22 17:41 UTC, alegoos commented on src/clients/FlexbaseClient.Company.ts
> +interface PaymentsResponse {
You could extend this interface with our `FlexbaseResponse` interface, and we can get the `success` and `error` values

```
interface PaymentsResponse extends FlexbaseResponse {
    payments?: Payment[];
};
```
The `payments` is optional if the function catch an error

2022-09-22 17:41 UTC, alegoos commented on src/clients/FlexbaseClient.Company.ts
> +    async getCompanyPayments(): Promise<Payment[] | null> {
I think putting a `null` response isn’t a good idea, we need good feedback if the response fails, and logged it, and I think we need to return the `success` value, where on the web repository we can manage these states.
You should leave the `promise` with the `PaymentsResponse`

```
    async getCompanyPayments(): Promise<PaymentsResponse> {
        try {
            const response = await this.client.url('/servicing/payments').get().json<PaymentsResponse>();
            if (!response.success) {
              this.logger.error('Some message error here', response.error);
          }
            return response;
        } catch (error) {
            this.logger.error(`Unable to get company payments`, error);
            return { success: false, error };
        }
    }
```

2022-09-22 18:05 UTC, alegoos approved these changes

2022-09-22 18:37 UTC, xXAndrexPereXx approved these changes

2022-09-22 18:38 UTC, merged

2023-10-17 20:39 UTC, tophercf commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/flexbase-eng/flexbase-client/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: