Add the result type to the Counterparty interface
flexbase-eng/flexbase-client pull request #55
Opened 2022-10-17 19:50 UTC by Mariana0711

DESCRIPTION

I created this PR to add the `response` object on the Counterparty interface, to get the `accountType` value and change the `name` type to `accountName` since the `GET /banking/{{companyId}}/moneymovement/counterparty/list` response looks like this 

```
{
    "success": true,
    "counterparties": [
        {
            "accessToken": "",
            "accountName": "Jane Doe",
            "accountNumber": "12345569",
            "asOf": "2022-10-17 16:46:01.713+00",
            "companyId": "3595cd4a-8e1e-4f8c-9ebb-beba1b998a0d",
            "createdAt": "2022-10-17 16:46:01.713+00",
            "id": "5c83c000-c7c8-4285-9600-83ce7d1e5553",
            "response": {
                "data": {
                    "attributes": {
                        "accountNumber": "12345569",
                        "accountType": "Checking",
                        "createdAt": "2022-10-17T16:46:01.669Z",
                        "name": "Jane Doe",
                        "permissions": "CreditOnly",
                        "routingNumber": "812345673",
                        "tags": {
                            "companyId": "3595cd4a-8e1e-4f8c-9ebb-beba1b998a0d",
                            "userId": "93916d46-170d-4de4-b916-6daaecf07b01",
                            "tenantId": "3595cd4a-8e1e-4f8c-9ebb-beba1b998a0d"
                        },
                        "type": "Person"
                    },
                    "id": "233414",
                    "relationships": {
                        "customer": {
                            "data": {
                                "id": "563348",
                                "type": "customer"
                            }
                        }
                    },
                    "type": "achCounterparty"
                }
            },
            "type": "achCounterparty",
            "ucCounterpartyId": "233414",
            "ucCustomerId": "563348",
            "userId": "93916d46-170d-4de4-b916-6daaecf07b01",
            "version": 1,
            "tenantId": "3595cd4a-8e1e-4f8c-9ebb-beba1b998a0d"
        }
    ]
}
```

2022-10-17 20:19 UTC, tophercf approved these changes, later dismissed

2022-10-17 20:20 UTC, kyle-b2 requested changes, later dismissed

2022-10-17 20:20 UTC, kyle-b2 commented on src/models/Banking/Counterparty.ts
> +            attributes: CounterpartyForm;
Can we have the attributes in this be at the top level?

2022-10-18 03:19 UTC, tophercf approved these changes, later dismissed

2022-10-18 14:57 UTC, kyle-b2 approved these changes
After this goes in we will need to update `flexbase-web` to use this version and update properties where they have changed

2022-10-18 15:00 UTC, tophercf approved these changes

2022-10-18 15:00 UTC, merged

2023-10-17 20:38 UTC, tophercf commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/flexbase-eng/flexbase-client/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: